### PR TITLE
[*] MO : Add short description into crossselling module

### PR DESCRIPTION
**Pull request by cdesbouche-acipia**
[*] MO (crossselling) : Add short description into crossselling module (template + controller)

Sorry for last pull request. Improvement added into template.

### CODE REVIEW

**Comment by jeromenadaud** [comment]
Hi,

Thank you for your contribution.

Best regards.

**Comment by jeromenadaud** [comment]
Hi,

If you want your change to be appear on default PrestaShop theme you will need to modify the same template in default-bootstrap/modules directory on PrestaShop.

Best regards

**Comment by vTerenti** [comment]
Hi,

Thank you for your contribution!

Don't you want to add the short description on the pop up in the Blockcart?

Best regards.

**Comment by cdesbouche-acipia** [comment]
Unfortunately, we use this feature only in crossseling module since we use essentially the declinaisons tab for your products and we consider our client knows what they add to cart.

**Comment by vTerenti** [comment]
Ok thanks for you answer! :)

Best regards!

**Pull request merged**
